# Generated by Django 4.0.1 on 2023-10-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_producturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('curr_time', models.DateTimeField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.listing')),
            ],
        ),
    ]
