# Generated by Django 4.0.1 on 2023-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='URL',
            field=models.ImageField(default=None, max_length=200, upload_to=''),
        ),
    ]
